#HADOOP VARIABLES START

    export JAVA_HOME=/usr/lib/jvm/java-8-oracle

    export HADOOP_INSTALL=/usr/local/hadoop

    export PATH=$PATH:$HADOOP_INSTALL/bin

    export PATH=$PATH:$HADOOP_INSTALL/sbin

    export HADOOP_MAPRED_HOME=$HADOOP_INSTALL

    export HADOOP_COMMON_HOME=$HADOOP_INSTALL

    export HADOOP_HDFS_HOME=$HADOOP_INSTALL

    export YARN_HOME=$HADOOP_INSTALL/yarn

    export HADOOP_COMMON_LIB_NATIVE_DIR=$HADOOP_INSTALL/lib/native

    export HADOOP_OPTS="-Djava.library.path=$HADOOP_INSTALL/lib/native"

#HADOOP VARIABLES END

export HIVE_HOME=/usr/local/hadoop/hive
export HCAT_HOME=$HIVE_HOME/hcatalog
export HIVE_CONF_DIR=$HIVE_HOME/conf
export HIVE_CLASS_PATH=$HIVE_CONF_DIR
export HIVE_AUX_JARS_PATH=/usr/local/hadoop/hive/lib
export CLASSPATH=$CLASSPATH:/usr/local/Hadoop/lib/*:.
export CLASSPATH=$CLASSPATH:/usr/local/hive/lib/*:.
export PATH=$PATH:$HIVE_HOME/bin:$HCAT_HOME/bin





export FLUME_HOME=/usr/local/hadoop/flume
export FLUME_CONF_DIR=$FLUME_HOME/conf
export FLUME_CLASSPATH=$FLUME_CONF_DIR
export CLASSPATH=$CLASSPATH:/FLUME_HOME/lib/*
export PATH=$PATH:$FLUME_HOME/bin/

